### ISSUE TITLE
Redirect/Remove 7 Nights Page

### ISSUE THREAD

**Issue by elyseandrews** [mswartz/somervillebeat#2]
I would like to redirect the current 7 Nights in Somerville page to the main Calendar page. I would also like to remove the 7 Nights page from the header.

**Comment by mswartz** [comment]
@elyseandrews sure thing. I'll make a 301 redirect so the old 7 nights URL goes to the calendar page and we can archive that page in the site (not delete it). And then I'll show you how to manage the header menu in the WP admin. I think we also need to remove the little house ad from the sidebar too.

**Comment by mswartz** [comment]
@elyseandrews this was actually way easier than i thought, so I just went and did it Here's what i did:
- Remove 7 nights from nav bar
- Remove house ad from sidebar
- create 301 redirect with WPEngine to redirect to `/events`

Take a look, but I'll close this issue for now.
